version: '2'
services:
    euroticketdemo-app:
        image: euroticketdemo
        external_links:
            - euroticketdemo-mysql:mysql
            - euroticketdemo-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/euroticketdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    euroticketdemo-mysql:
        extends:
            file: mysql.yml
            service: euroticketdemo-mysql
    euroticketdemo-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: euroticketdemo-elasticsearch
