version: '2'
services:
    euroticketdemo-elasticsearch:
        container_name: euroticketdemo-elasticsearch
        image: elasticsearch:1.7.5
        # volumes:
        #     - ~/volumes/jhipster/EuroTicketDemo/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
